Randomized string concat
fastruby/fast-ruby pull request #216
Opened 2022-11-12 09:49 UTC by alekseyl

proposition for https://github.com/fastruby/fast-ruby/issues/158 fix.

2023-01-05 21:25 UTC, JuanVqz reviewed
Hey, @alekseyl thank you for the time you spent on this, it looks good, I just left some minor comments, let me know what you think :+1:

2023-01-07 12:20 UTC, alekseyl commented
Thnx @JuanVqz, no worries for the delay :). I've commited suggested!

2023-01-12 16:03 UTC, JuanVqz commented on code/string/concatenation_randomized.rb
> +end
```suggestion
def bench_10_to_100
  Benchmark.bmbm do |x|
    sarr1 = Array.new(2_000_000) { RandStr.eq100.dup }
    sarr2 = Array.new(2_000_000) { RandStr.eq100.dup }
  
    i, j = 0, 0
    x.report("Collateral actions only")  { k=0; 1_000_000.times { k+=1; RandStr.eq10; sarr2[k]; RandStr.lt100; } }
    x.report("String#+")         { k=0; 1_000_000.times { k+=1; sarr1[k]; fastest_plus(RandStr.eq10, RandStr.lt100) } }
    x.report('"#{foo}#{bar}"')   { k=0; 1_000_000.times { k+=1; sarr2[k]; fast_interpolation(RandStr.eq10, RandStr.lt100) } }
    x.report("String#concat")    { 1_000_000.times { RandStr.eq10; slow_concat(sarr1[i], RandStr.lt100); i+=1; } }
    x.report("String#append")    { 1_000_000.times { RandStr.eq10; slow_append(sarr2[j], RandStr.lt100); j+=1;  } }
  end
end
```

2023-01-12 16:05 UTC, JuanVqz approved these changes
@alekseyl, Thank you for your contribution, it looks good :+1:

2023-01-12 19:16 UTC, JuanVqz commented
@mateusdeap could you please have a look to merge it?

2023-03-02 15:43 UTC, etagwerker requested changes
@alekseyl @JuanVqz I noticed that this PR uses `bmbm` and we want all benchmarks to use `ips`

Could you please tweak this benchmark to use "benchmark/ips"? 

It shouldn't affect the results. 

Thanks!

2023-04-16 13:25 UTC, alekseyl commented
> @alekseyl @JuanVqz I noticed that this PR uses bmbm and we want all benchmarks to use ips
> Could you please tweak this benchmark to use "benchmark/ips"?
> It shouldn't affect the results.
> Thanks!

@etagwerker Hi Ernesto!

Sorry for the delayed answer. The problem is it will not look as good as we migh expect, because of a randomization )). It will show a much bigger variance (20-30-40% I can't recall properly) over relatively "small" difference. 

I might give it a try one more time, but can't promise that it will be soon enough :(. I need an inspiration to dive in to that river again  ))).

2023-04-27 01:08 UTC, ixti commented
Can we also add:

``` ruby
[foo, bar].join
```

It would also make sense to check if there will be different results with more than 2 strings to concatenate. Also, would be nice to see performance comparison of cases like:

``` ruby
"#{foo}-#{bar}"
```

2023-06-17 00:57 UTC, etagwerker approved these changes
@alekseyl Looks good, thank you!

2023-06-17 00:58 UTC, merged